"""initial schema

Revision ID: 63bd06093753
Revises: 
Create Date: 2025-08-20 05:28:52.380050
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '63bd06093753'
down_revision = None
branch_labels = None
depends_on = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'rent_form',
        sa.Column('id', sa.Integer(), primary_key=True),
        sa.Column('name', sa.String(length=120), nullable=False),
        sa.Column('transaction_id', sa.String(length=120), nullable=False),
    )
    op.create_table(
        'pending_booking',
        sa.Column('id', sa.Integer(), primary_key=True),
        sa.Column('canoe_count', sa.Integer(), nullable=False),
        sa.Column('participant_names', sa.Text(), nullable=False),
        sa.Column('status', sa.String(length=20), nullable=False, server_default='pending'),
    )
    op.create_table(
        'users',
        sa.Column('id', sa.Integer(), primary_key=True),
        sa.Column('username', sa.String(length=80), nullable=False, unique=True),
        sa.Column('pw_hash', sa.String(length=128), nullable=False),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    op.drop_table('pending_booking')
    op.drop_table('rent_form')
    # ### end Alembic commands ###
